### ISSUE TITLE
Does evcache plan to support the memcached namespace?

### ISSUE THREAD

**Issue by shengang1978** [Netflix/EVCache#58]
In our scene， we need flush several caches which are associated with one value. For example, user profile, score and other user info, when user updates his/her info, we need update all the caches which are related to the user. 
Currently, we use another cache entry to store all the user keys. Then we get all the keys by the cached entry and flush them. We meet some problems on this solution.
1. Sometimes, the cached entry is expired or evicted. We cannot get the cache keys to flush.
2. The performance is not high. It needs 3 operations to store a data to cache. (1 query and 1 set for the cache entry, and another 1 to store the data)
3. The cache entry data may be dirty because there are several servers which update the cache entry. 

Do you have the same scene? And how do you resolve it if have?

**Comment by smadappa** [comment]
1. You can set the TTL for the key that stores all user keys to 0 meaning never expire. It might get evicted but if you keep touching it, it might not. If it gets evicted then you have orphan keys so you need to figure out a strategy so that this does not happen.

2. You don't have to read-modify-write. You can use add, append or appendOrAdd api. 

3. Using append avoids that so you don't miss any update. You might have duplicates but should be fine as you are guaranteed that you process the key at least once.

**Comment by shengang1978** [comment]
We use the appendOrAdd to manage the group of the keys. It can resolve most problems.
